### ISSUE TITLE
关于有符号二进制加法运算的一些疑问

### ISSUE THREAD

**Issue by Ethanzyc** [algorithmzuo/algorithm-journey#7]
左神您好，我是一个算法新人，也是您的粉丝，我在 b 站 003 讲关于二进制的视频中评论，大概意思是有符号二进制的最高位可以看做一个负值，而不是看作符号，比如 4 位 2 进制，最高位可以看成是 -8，用这个去转十进制或者做加法计算，然后好像账号就被拉黑了，想问下这个是有哪边理解不对吗？或者说这个是会误导别人吗？希望左神看到能抽空解答一下，多谢

**Comment by algorithmzuo** [comment]
我不希望在我的视频账号下，看到没啥建设性的意见。

**Comment by Ethanzyc** [comment]
绝对没有意见，可能视角不一样，我感觉评论可能是和其他看您视频的一起讨论的地方，您这边可能觉得我是在对您说，虽然我这边看不到当时评论了什么，但可能语气有点冒犯，但确实是想讨论一下，并不是意见，已经是二刷您的视频，觉得是我看过最好的算法视频，绝对没有意见，如果您觉得这样能舒服点，那就拉黑吧，还是说声谢谢，毕竟看了这么久，也学到了很多，抱拳！
